Add CVE-2020-7354 and CVE-2020-7355 for Metasploit
rapid7/cvelist pull request #26
Opened 2020-06-22 14:20 UTC by todb-r7

For the recent Metasploit Pro bugs, discussed in issue 7104 in the security ticket queue.

@djordan-r7, can you take a look for spelling and grammar and sensibility? If you have any question, just hit me up on Slack.

2020-06-22 14:32 UTC, todb-r7 commented
btw I like how my signed commit totally failed here. whoops. I'll sign it when I push it up to MITRE.

2020-06-24 10:55 UTC, djordan-r7 commented on 2020/7xxx/CVE-2020-7354.json
> +                "value": "Cross-site Scripting (XSS) vulnerability in the 'host' field of a discovered scan asset in Rapid7 Metasploit Pro allows an attacker with a specially-crafted network service
"...specially-crafted network service of a scan target to store an XSS sequence in the Metasploit Pro console..."

2020-06-24 10:57 UTC, djordan-r7 commented on 2020/7xxx/CVE-2020-7354.json
> +                "value": "Cross-site Scripting (XSS) vulnerability in the 'host' field of a discovered scan asset in Rapid7 Metasploit Pro allows an attacker with a specially-crafted network service
Shouldn't it be CVE-2020-7355 which affects the 'notes' field?

2020-06-24 11:00 UTC, djordan-r7 requested changes
@todb-r7 just a couple of minor changes :)

2020-06-24 18:19 UTC, todb-r7 commented on 2020/7xxx/CVE-2020-7354.json
> +                "value": "Cross-site Scripting (XSS) vulnerability in the 'host' field of a discovered scan asset in Rapid7 Metasploit Pro allows an attacker with a specially-crafted network service
Derp, of course.

2020-06-24 18:36 UTC, todb-r7 commented on 2020/7xxx/CVE-2020-7354.json
> +                "value": "Cross-site Scripting (XSS) vulnerability in the 'host' field of a discovered scan asset in Rapid7 Metasploit Pro allows an attacker with a specially-crafted network service
7354 should be for 'host', 7355 should be 'notes' -- is this not the case? Copy pasting nearly the same thing always screws up something somewhere, but basically:

* CVE-2020-7354 should have the 'host' title and description, but also reference the 'notes' bug in 7355.
* CVE-2020-7355 should have the 'notes' title and description, but also reference the 'host' bug in 7354.

Is this not the case here? I've read it like 10 times and not seeing a mis-identification here (after my latest commit). You /should/ have the rights to edit the msp-xss branch if you can see something I'm not seeing.

2020-06-25 17:11 UTC, todb-r7 commented on 2020/7xxx/CVE-2020-7354.json
> +                "value": "Cross-site Scripting (XSS) vulnerability in the 'host' field of a discovered scan asset in Rapid7 Metasploit Pro allows an attacker with a specially-crafted network service
Re-reviewing, this looks good to me, now. Thanks for the review, @djordan-r7 !

2020-06-25 17:12 UTC, todb-r7 reviewed
Fixed and committed!

2020-06-25 17:12 UTC, merged