Add CVEs for two Metasploit modules
rapid7/cvelist pull request #30
Opened 2020-08-24 15:18 UTC by todb-r7

Covers the issues discussed at rapid7/metasploit-framework#14008 and rapid7/metasploit-framework#14015

@bcoles feel free to take a look and tell me if something is grossly wrong! I always feel like I'm just guessing at CVSS scores, they get rewritten upstream anyway by NVD (nobody believes the issuer of CVEs for CVSS, turns out).

2020-08-24 15:28 UTC, djordan-r7 commented on 2020/7xxx/CVE-2020-7377.json
> +        "TITLE": "Rapid7 Metasploit Framework Pelative Path Traversal in telpho10_credential_dump module"
"Pelative Path Traversal" - should be Relative Path Traversal?

2020-08-24 15:32 UTC, djordan-r7 requested changes
Just one copypaste error!

2020-08-24 15:32 UTC, todb-r7 commented on 2020/7xxx/CVE-2020-7377.json
> +        "TITLE": "Rapid7 Metasploit Framework Pelative Path Traversal in telpho10_credential_dump module"
Fixed!

2020-08-24 17:26 UTC, bcoles commented on 2020/7xxx/CVE-2020-7377.json
> +                                            "version_value": "6.0.2"
This issue has not yet been fixed. Presuming that my open PR (https://github.com/rapid7/metasploit-framework/pull/14034) is reviewed, found to be sufficient, and merged this week, the versions affected would be `< 6.0.3`.

2020-08-24 17:26 UTC, bcoles commented on 2020/7xxx/CVE-2020-7377.json
> +            "value": "Users should update to version 6.0.2 or later of the Metasploit Framework."
`6.0.3` as above.

2020-08-24 19:00 UTC, todb-r7 commented on 2020/7xxx/CVE-2020-7377.json
> +                                            "version_value": "6.0.2"
Ah, thanks. Will update both!

2020-08-24 19:05 UTC, todb-r7 reviewed
Updated!

2020-08-24 19:05 UTC, todb-r7 commented
Man all these fancy Github review buttons. Never mind! All edits made, gtg now. Thanks!

2020-08-24 19:06 UTC, merged

2020-08-25 14:38 UTC, bcoles commented on 2020/7xxx/CVE-2020-7377.json
> +                                            "version_value": "6.0.2"
No need to update both.

CVE-2020-7376 was resolved in 6.0.2.

CVE-2020-7377 has now been patched and the patch will be available in the 6.0.3 release this week.