Add Matthew's OpenNMS bugs
rapid7/cvelist pull request #44
Opened 2021-09-10 22:44 UTC by todb-r7

Poke @mkienow-r7 to eyeball these for errors, then @todb-r7 will send 'em along to upstream.

2021-09-10 23:32 UTC, mkienow-r7 requested changes

2021-09-10 23:32 UTC, mkienow-r7 commented on 2016/6xxx/CVE-2016-6555.json
> +        "DATE_PUBLIC": "2016-09-14T18:18:00.000Z",
The blog shows "Nov 15, 2016"

2021-09-10 23:32 UTC, mkienow-r7 commented on 2016/6xxx/CVE-2016-6555.json
> +                "value": "OpenNMS version 18.0.1 and prior are vulnerable to a stored XSS issue due to insufficient filtering of SNMP trap supplied data. By creating a malicious SNMP trap, an attacke
If you want to be specific replace "views the data" with "views the events list page".

2021-09-10 23:32 UTC, mkienow-r7 commented on 2016/6xxx/CVE-2016-6556.json
> +                "value": "OpenNMS version 18.0.1 and prior are vulnerable to a stored XSS issue due to insufficient filtering of SNMP agent supplied data. By creating a malicious SNMP 'sysName' respo
'sysName' or 'sysContact' response

2021-09-10 23:32 UTC, mkienow-r7 commented on 2016/6xxx/CVE-2016-6555.json
> +                "value": "OpenNMS version 18.0.1 and prior are vulnerable to a stored XSS issue due to insufficient filtering of SNMP trap supplied data. By creating a malicious SNMP trap, an attacke
"18.0.2-1" to match the other CVE description

2021-09-10 23:35 UTC, todb-r7 commented on 2016/6xxx/CVE-2016-6555.json
> +        "DATE_PUBLIC": "2016-09-14T18:18:00.000Z",
￼Indeed, but the PR was public earlier so I'm figuring that's the public date of the vuln. (That's the first time anyone knew about it who cared to look.)

2021-09-10 23:44 UTC, mkienow-r7 commented on 2016/6xxx/CVE-2016-6555.json
> +        "DATE_PUBLIC": "2016-09-14T18:18:00.000Z",
Okay, that makes sense!

2021-09-11 00:01 UTC, todb-r7 commented on 2016/6xxx/CVE-2016-6555.json
> +                "value": "OpenNMS version 18.0.1 and prior are vulnerable to a stored XSS issue due to insufficient filtering of SNMP trap supplied data. By creating a malicious SNMP trap, an attacke
Yeah meant to change it here, the final release was just 18.0.2

2021-09-11 00:04 UTC, merged